[build]
  publish = "."

# Netlify Forms configuration
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

# Redirects for clean URLs and SEO
[[redirects]]
  from = "/docs"
  to = "/docs.html"
  status = 301

[[redirects]]
  from = "/faq"
  to = "/faq.html"
  status = 301

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/privacy.html"
  status = 301

[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 301

# Force HTTPS redirects
[[redirects]]
  from = "http://stroku.netlify.app/*"
  to = "https://stroku.netlify.app/:splat"
  status = 301
  force = true

# Headers for SEO and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/googleec4fffb134df3d55.html"
  [headers.values]
    Content-Type = "text/html"
